# Objective: leasrn to provisiong multiple (multiple OS)
# Using Conditions and Loop

---
- name: Provisioning Servers
  hosts: all
  become: yes
  tasks:
    - name: Install packages on CentOS
      yum:
        # we are using loop here so the parameter is "{{item}}"
        name: "{{item}}"
        state: present
      # Use condition "When" here to avoid yum command being run on Ubuntu Server
      when: ansible_distribution == "CentOS"
      # Use loop here to run yum install agaist all pakages
      loop:
        - ntp
        - wget
        - git
        - zip
        - unzip

    - name: Install packages on Ubuntu
      apt:
        name: "{{item}}"
        state: present
        # to run apt update before it installs a package
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
      loop:
        - ntp
        - wget
        - git
        - zip
        - unzip

    - name: Start & enable NTP on Redhat
      service:
        name: ntpd
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"
    - name: Start & enable NTP on Debian
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"
    - name: Add group
      group:
        name: devops
        state: present
    - name: Add users
      user:
        name: "{{item}}"
        state: present
        groups: devops
      loop:
        - user1
        - user2
        - user3
        - user4

